### PR TITLE
#3 Added Splash Screen

### PR DESCRIPTION
**Pull request by heyprincesingh**
Added a splash screen by adding the application logo and the tagline demanded. 
Please have a look and consider my pull request.
Thank you!

### CODE REVIEW

**Comment by heyprincesingh** [comment]
#3 Completed the issue. Please review it and merge if no issue found or contact if found any issue.

**Comment by syedzubeen** [comment]
Will review and update, if any changes are required. 😃

**Comment by heyprincesingh** [comment]
> Will review and update, if any changes are required. 😃

Sure! Thanks🎉

**Comment by heyprincesingh** [comment]
> Will review and update, if any changes are required. 😃

Hey! did you went through this PR?
If any issue please tell and if not please merge it if possible...

**Pull request closed without merging**
